<?php
require_once dirname(__DIR__) . '/core/Controller.php'; require_once dirname(__DIR__) . '/models/PurchaseOrder.php'; require_once dirname(__DIR__) . '/models/Supplier.php';
class PurchasesController extends Controller {
 private PurchaseOrder $model; private Supplier $suppliers;
 public function __construct(){ $this->model=new PurchaseOrder(); $this->suppliers=new Supplier(); }
 public function index(): void { $this->requireModuleAccess('purchases', ['Administrator','Procurement Officer','Store Officer']); $this->view('purchases/index',['title'=>'Purchases','orders'=>$this->model->all(),'suppliers'=>$this->suppliers->all(),'error'=>$_SESSION['flash_error']??null]); unset($_SESSION['flash_error']); }
 public function create(): void { $this->requireLogin(); if($_SERVER['REQUEST_METHOD']==='POST'){ if(!$this->validateCsrf()){$_SESSION['flash_error']='Invalid security token';$this->redirect('/index.php?controller=purchases');} $supplierId = (int)($_POST['supplier_id'] ?? 0); $orderedBy = (int)($_SESSION['user']['id'] ?? 0); $this->model->create($_POST+['ordered_by'=>$orderedBy]); if($supplierId > 0){ notifyTeam(['Administrator','Procurement Officer','Store Officer'], 'Purchase order created', 'A new purchase order has been created for supplier ID #' . $supplierId . '.'); } } $this->redirect('/index.php?controller=purchases'); }
 public function status(): void { $this->requireLogin(); if($_SERVER['REQUEST_METHOD']==='POST' && $this->validateCsrf()){ $orderId = $this->sanitizeInt($_POST['id'] ?? 0); $status = $this->sanitize($_POST['status'] ?? 'pending'); $this->model->updateStatus($orderId, $status); $order = $this->model->find($orderId); if($order && (int)($order['ordered_by'] ?? 0) > 0){ createNotification((int)($order['ordered_by'] ?? 0), 'Purchase order update', 'Your purchase order #' . $orderId . ' is now marked as ' . $status . '.'); } } $this->redirect('/index.php?controller=purchases'); }
}
