<div class="mb-4"><h1 class="page-title">Reports</h1><p class="page-subtitle">Create an auditable record of operational reports generated by the team.</p></div>
<div class="card mb-4">
	<div class="card-body">
		<div class="d-flex justify-content-between align-items-start gap-3 mb-3">
			<div><h5 class="mb-1">AI business insights</h5><p class="text-secondary small mb-0">Ask about recent sales, low stock, and purchase orders. Aggregated operational data and your question are sent to the configured AI provider. Do not include personal or confidential information.</p></div>
			<span class="badge text-bg-light">OpenRouter</span>
		</div>
		<form id="ai-insights-form" class="vstack gap-3" action="?controller=reports&amp;action=ask" method="post">
			<?= $this->csrfField() ?>
			<label class="visually-hidden" for="ai-insights-question">Question</label>
			<textarea class="form-control" id="ai-insights-question" name="question" rows="2" maxlength="1000" placeholder="What should I pay attention to in the latest stock and sales figures?" required></textarea>
			<div class="d-flex flex-wrap align-items-center gap-2">
				<button class="btn btn-primary" id="ai-insights-submit" type="submit"><i class="fa-solid fa-wand-magic-sparkles me-2" aria-hidden="true"></i>Ask for insights</button>
				<span class="small text-secondary" id="ai-insights-status" role="status" aria-live="polite"></span>
			</div>
		</form>
		<div class="alert alert-light border mt-3 mb-0 d-none ai-insights-answer" id="ai-insights-answer" role="region" aria-label="AI response" aria-live="polite"><div class="ai-insights-markdown"></div></div>
	</div>
</div>
<div class="ai-toast-stack" id="ai-toast-stack" aria-live="polite" aria-relevant="additions"></div>
<div class="row g-4"><div class="col-lg-5"><div class="card"><div class="card-body"><h5>Generate report record</h5><form method="post" action="?controller=reports&action=generate" class="vstack gap-3"><?= $this->csrfField() ?><input class="form-control" name="report_name" placeholder="Report name" required><select class="form-select" name="report_type"><option>Sales summary</option><option>Inventory valuation</option><option>Receivables</option><option>GPS activity</option><option>Cash book</option></select><textarea class="form-control" name="filters" placeholder="Filters or reporting period"></textarea><button class="btn btn-primary">Save report</button></form></div></div></div><div class="col-lg-7"><div class="card"><div class="card-body"><h5>Generated reports</h5><div class="table-responsive"><table class="table"><thead><tr><th>Name</th><th>Type</th><th>Generated by</th><th>Date</th></tr></thead><tbody><?php foreach($reports as $r): ?><tr><td><?= htmlspecialchars($r['report_name']) ?></td><td><?= htmlspecialchars($r['report_type']) ?></td><td><?= htmlspecialchars($r['generated_by_name']??'System') ?></td><td><?= htmlspecialchars($r['generated_at']) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></div></div>
<script>
(() => {
	const form = document.getElementById('ai-insights-form');
	const submit = document.getElementById('ai-insights-submit');
	const status = document.getElementById('ai-insights-status');
	const answer = document.getElementById('ai-insights-answer');
	const answerContent = answer.querySelector('.ai-insights-markdown');
	const toastStack = document.getElementById('ai-toast-stack');

	const showToast = (message, type = 'success') => {
		const toast = document.createElement('div');
		toast.className = `ai-toast ai-toast-${type}`;
		toast.setAttribute('role', type === 'error' ? 'alert' : 'status');
		const icon = document.createElement('i');
		icon.className = type === 'error' ? 'fa-solid fa-circle-exclamation' : 'fa-solid fa-circle-check';
		icon.setAttribute('aria-hidden', 'true');
		const text = document.createElement('span');
		text.textContent = message;
		const close = document.createElement('button');
		close.type = 'button';
		close.className = 'ai-toast-close';
		close.setAttribute('aria-label', 'Dismiss notification');
		close.textContent = '\u00d7';
		close.addEventListener('click', () => toast.remove());
		toast.append(icon, text, close);
		toastStack.append(toast);
		window.setTimeout(() => toast.remove(), 6000);
	};

	const appendInlineMarkdown = (parent, text) => {
		const pattern = /(\*\*[^*]+\*\*|__[^_]+__|`[^`]+`|\*[^*]+\*|_[^_]+_)/g;
		let cursor = 0;

		for (const match of text.matchAll(pattern)) {
			parent.append(document.createTextNode(text.slice(cursor, match.index)));
			const token = match[0];
			const isBold = token.startsWith('**') || token.startsWith('__');
			const isCode = token.startsWith('`');
			const element = document.createElement(isBold ? 'strong' : isCode ? 'code' : 'em');
			element.textContent = token.slice(isBold ? 2 : 1, -(isBold ? 2 : 1));
			parent.append(element);
			cursor = match.index + token.length;
		}

		parent.append(document.createTextNode(text.slice(cursor)));
	};

	const renderMarkdown = (markdown) => {
		answerContent.replaceChildren();
		let paragraphLines = [];
		let listElement = null;
		let listType = '';

		const flushParagraph = () => {
			if (!paragraphLines.length) return;
			const paragraph = document.createElement('p');
			paragraph.className = 'mb-2';
			appendInlineMarkdown(paragraph, paragraphLines.join(' '));
			answerContent.append(paragraph);
			paragraphLines = [];
		};

		const flushList = () => {
			listElement = null;
			listType = '';
		};

		for (const line of markdown.split(/\r?\n/)) {
			const trimmed = line.trim();
			if (!trimmed) {
				flushParagraph();
				flushList();
				continue;
			}

			const headingMatch = trimmed.match(/^(#{1,3})\s+(.+)$/);
			if (headingMatch) {
				flushParagraph();
				flushList();
				const heading = document.createElement(headingMatch[1].length === 1 ? 'h5' : 'h6');
				heading.className = 'mt-3 mb-2';
				appendInlineMarkdown(heading, headingMatch[2]);
				answerContent.append(heading);
				continue;
			}

			const listMatch = trimmed.match(/^([-*+]\s+|\d+[.)]\s+)(.+)$/);
			if (listMatch) {
				flushParagraph();
				const nextListType = /^\d/.test(listMatch[1]) ? 'ol' : 'ul';
				if (listElement && listType !== nextListType) flushList();
				if (!listElement) {
					listType = nextListType;
					listElement = document.createElement(listType);
					listElement.className = 'mb-2 ps-4';
					answerContent.append(listElement);
				}
				const item = document.createElement('li');
				appendInlineMarkdown(item, listMatch[2]);
				listElement.append(item);
				continue;
			}

			flushList();
			paragraphLines.push(trimmed);
		}

		flushParagraph();
	};

	form.addEventListener('submit', async (event) => {
		event.preventDefault();
		submit.disabled = true;
		const originalButtonContent = submit.innerHTML;
		submit.innerHTML = '<i class="fa-solid fa-spinner fa-spin me-2" aria-hidden="true"></i>Generating';
		status.textContent = 'Generating insights…';

		try {
			const response = await fetch(form.action, { method: 'POST', body: new FormData(form), headers: { 'Accept': 'application/json' } });
			let result;
			try {
				result = await response.json();
			} catch {
				throw new Error('The server returned an unreadable response. Please refresh and try again.');
			}
			if (!response.ok || !result.ok) throw new Error(typeof result.error === 'string' ? result.error : 'Unable to generate insights.');
			if (typeof result.answer !== 'string' || !result.answer.trim()) throw new Error('The AI service returned an empty response. Please try again.');
			renderMarkdown(result.answer);
			answer.classList.remove('d-none');
			status.textContent = '';
			showToast('AI insights are ready.');
		} catch (error) {
			const message = error instanceof TypeError
				? 'Could not connect to the server. Check your connection and try again.'
				: (error.message || 'Unable to generate insights. Please try again.');
			status.textContent = message;
			showToast(message, 'error');
		} finally {
			submit.disabled = false;
			submit.innerHTML = originalButtonContent;
		}
	});
})();
</script>
<style>
	.ai-toast-stack { position: fixed; right: 22px; bottom: 22px; z-index: 1080; display: grid; gap: 10px; width: min(390px, calc(100vw - 28px)); }
	.ai-toast { display: grid; grid-template-columns: 20px minmax(0, 1fr) 28px; align-items: start; gap: 10px; padding: 14px 12px; border: 1px solid #d8e7df; border-left: 4px solid #16845b; border-radius: 8px; background: #fff; color: #20352c; box-shadow: 0 10px 30px rgba(20, 35, 28, .16); font-size: 13px; animation: ai-toast-in .18s ease-out; }
	.ai-toast > i { color: #16845b; margin-top: 2px; }
	.ai-toast-error { border-color: #f0d4d4; border-left-color: #bd3f45; color: #49282a; }
	.ai-toast-error > i { color: #bd3f45; }
	.ai-toast-close { border: 0; background: transparent; color: #6c7882; font-size: 20px; line-height: 1; padding: 0; }
	.ai-toast-close:hover { color: #17202a; }
	.ai-insights-answer p:last-child, .ai-insights-answer ul:last-child, .ai-insights-answer ol:last-child { margin-bottom: 0 !important; }
	@keyframes ai-toast-in { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }
	@media (prefers-reduced-motion: reduce) { .ai-toast { animation: none; } }
</style>
